import { useQuery } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import type { Tables, Json } from '@/integrations/supabase/types';
export type Content = Tables<'platform_content'>;
export function details(item: Content): Record<string, string> { return (item.details && typeof item.details === 'object' && !Array.isArray(item.details) ? item.details : {}) as Record<string,string>; }
export function useContent(kind?: string) { return useQuery({ queryKey: ['content',kind], queryFn: async () => { let q=supabase.from('platform_content').select('*').in('status',['published','scheduled','closed']).lte('published_at',new Date().toISOString()).order('published_at',{ascending:false}); if(kind) q=q.eq('kind',kind); const {data,error}=await q; if(error) throw error; return data ?? []; }}); }
export function availability(item: Content) { if(item.status==='closed'||(item.deadline && Date.parse(item.deadline)<=Date.now())) return 'CLOSED'; if(item.deadline && Date.parse(item.deadline)-Date.now()<7*86400000) return 'CLOSING SOON'; return 'OPEN'; }
export const categories=['Community Outreach','Youth','Education','Mental Health','Environment','Project Green Kenya','Healthcare','Partnerships','Opportunities','Announcements','Events','Success Stories','Leadership'];
export const volunteerAreas=['Community Outreach','Youth Empowerment','Education','Mental Health','Environment','Project Green Kenya','Healthcare','Media','Photography/Videography','Technology','Graphic Design','Research','Fundraising','Events','Administration','Other'];
export const opportunityCategories=['Jobs','Internships','Industrial Attachments','Volunteer Opportunities','Fellowships','Scholarships','Training','Consultancies','Project Positions','Youth Opportunities','Leadership Opportunities','Other Opportunities'];
export const partnerCategories=['Government Institutions','NGOs & Foundations','CBOs & Community Organizations','Companies & CSR Programs','Schools','Universities & TVET Institutions','Healthcare Institutions','Professional Associations','Media Organizations','Faith-Based Organizations','Youth Organizations','Development Partners','Individual Professionals'];
export const areas=[['Youth Empowerment','Supporting young people through leadership, mentorship, skills development, opportunities and community participation.'],['Education Support','Promoting access to educational opportunities, mentorship, learning resources and academic and professional pathways.'],['Mental Health Awareness','Promoting emotional wellbeing, supportive conversations and appropriate information and referral pathways.'],['Community Outreach','Community-centered awareness, humanitarian support, health-related activities and youth engagement.'],['Environmental Action','Project Green Kenya: plastic recovery, recycling, upcycling, environmental education and community climate action.'],['Skills & Entrepreneurship','Practical skills, entrepreneurship and connections to opportunities.'],['Inclusion & Community Support','Inclusive participation and support for vulnerable and underserved communities.'],['Partnerships & Collaboration','Working with institutions, professionals, businesses and community groups for sustainable initiatives.']];
export const assetUrl=(url:string)=>url.startsWith('/__l5e/') && ['localhost','127.0.0.1'].includes(window.location.hostname)?`https://id-preview--7235d861-658c-4712-8e7a-22f0d89ebb51.lovable.app${url}`:url;
export const safeUrl=(url?: string|null)=>url && (/^https?:\/\//.test(url)||url.startsWith('/')) ? assetUrl(url) : undefined;
export type Payload = Record<string, Json>;
