import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { supabase } from '@/integrations/supabase/client';
import { useContent, details, safeUrl, type Content } from './data';
import abigail from '@/assets/abigail-isika.jpg';
import zachariah from '@/assets/zachariah-manani.png';
import farm from '@/assets/smart-farm.jpg';
import m5 from '@/assets/m5-logo.png';
import athena from '@/assets/athena-2.jpg';
export const imageFor=(item:Content)=>safeUrl(item.image_url)??({abigail,zachariah,farm,m5} as Record<string,string>)[details(item).photo_key]??(item.slug==='athena-school-endometriosis-outreach'?athena:undefined);
export function Section({id,title,eyebrow,children,tone=false}:{id?:string;title:string;eyebrow?:string;children:React.ReactNode;tone?:boolean}){return <section id={id} className={`py-14 md:py-20 scroll-mt-20 ${tone?'bg-card border-y border-border':'bg-background'}`}><div className="container mx-auto px-4"><div className="mb-8">{eyebrow&&<p className="text-accent text-xs uppercase font-semibold mb-3">{eyebrow}</p>}<h2 className="font-display text-2xl md:text-3xl font-bold">{title}</h2></div>{children}</div></section>}
export function ContentStatus({loading,error}:{loading:boolean;error:unknown}){return loading?<p role="status">Loading…</p>:error?<p role="alert" className="text-destructive">This content could not be loaded. Please refresh or contact Mabawa.</p>:null;}
export function Metrics(){const q=useContent('metric');const labels=['Young People Engaged','Communities Reached','Outreach Activities','Volunteers','Schools Reached','Projects Implemented','Partnerships','Training Participants'];return <><ContentStatus loading={q.isLoading} error={q.error}/><div className="grid grid-cols-2 lg:grid-cols-4 gap-5">{labels.map(label=>{const item=q.data?.find(i=>i.title===label);return <div key={label} className="border border-border rounded-lg p-5 bg-background"><p className="font-display text-2xl font-bold text-primary">{item?details(item).value||'Updating…':'Updating…'}</p><p className="text-sm text-muted-foreground mt-2">{label}</p></div>;})}</div></>}
export function StoryCards({items}:{items:Content[]}){return <div className="grid md:grid-cols-3 gap-6">{items.map(item=><article key={item.id} className="border border-border rounded-lg overflow-hidden bg-background">{imageFor(item)&&<Link to={`/news/${item.slug}`}><img src={imageFor(item)} alt={item.title} className="w-full h-56 object-contain bg-muted" loading="lazy"/></Link>}<div className="p-6"><p className="text-accent text-xs font-semibold">{item.category} · {new Date(item.published_at).toLocaleDateString('en-KE')}</p><h3 className="font-display font-bold text-xl my-3"><Link to={`/news/${item.slug}`}>{item.title}</Link></h3><p className="text-muted-foreground text-sm leading-relaxed mb-5">{item.excerpt}</p><Button asChild variant="outline"><Link to={`/news/${item.slug}`}>Read More →</Link></Button></div></article>)}</div>}
export function Subscribe({alerts=false}:{alerts?:boolean}){const[done,setDone]=useState(false),[token,setToken]=useState<string|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);return done?<div role="status"><p>Thank you. Your subscription request has been saved.</p>{token&&<Link className="text-primary underline text-sm" to={`/unsubscribe?token=${token}`}>Unsubscribe from these updates</Link>}<p className="text-muted-foreground text-sm mt-2">To stop existing updates, use the unsubscribe link supplied with your subscription or contact Mabawa.</p></div>:<form className="space-y-4" onSubmit={async e=>{e.preventDefault();setBusy(true);const fd=new FormData(e.currentTarget);const {data,error}=await supabase.rpc('subscribe_platform',{_email:String(fd.get('email')),_name:String(fd.get('full_name')??''),_categories:fd.getAll('categories').map(String)});setBusy(false);if(error)setError(error.message);else{setToken(data);setDone(true);}}}><label className="block text-sm">Name<Input className="mt-2 bg-background" name="full_name"/></label><label className="block text-sm">Email<Input className="mt-2 bg-background" name="email" type="email" required/></label>{alerts&&<fieldset className="flex flex-wrap gap-4"><legend className="text-sm font-medium mb-3">Opportunity alerts</legend>{['Jobs','Internships','Scholarships','Fellowships','Training','Volunteering','Events','Youth Opportunities','Climate'].map(c=><label className="text-sm flex items-center gap-2" key={c}><input type="checkbox" name="categories" value={c}/>{c}</label>)}</fieldset>}<label className="text-sm flex gap-2"><input type="checkbox" required/>I agree to receive Mabawa updates.</label>{error&&<p role="alert" className="text-destructive">{error}</p>}<Button disabled={busy}>{busy?'Saving…':'Subscribe'}</Button></form>}
export function PartnersDirectory(){const q=useContent('partner');return <><ContentStatus loading={q.isLoading} error={q.error}/><div className="grid md:grid-cols-3 gap-6">{q.data?.map(i=><article className="border border-border rounded-lg p-6 bg-background" key={i.id}>{imageFor(i)&&<img src={imageFor(i)} alt={`${i.title} logo`} className="h-20 max-w-full object-contain mb-5"/>}<h3 className="font-display text-xl font-bold">{i.title}</h3><p className="text-accent text-sm mt-2">{details(i).project?"Outreach collaboration":i.category}</p><p className="text-muted-foreground mt-4">{i.body}</p>{safeUrl(details(i).website)&&<a className="text-primary underline mt-4 block" href={safeUrl(details(i).website)} target="_blank" rel="noopener noreferrer">Visit partner website</a>}</article>)}</div></>}
